/**
 * Created by Seven on 2019/3/30.
 * project: AutumnUI
 * email: fighting20xx@126.com
 */


export const iconList = [
	"iconappreciate",
	 "iconcheck",
	 "iconclose",
	 "iconedit",
	 "iconemoji",
	 "iconfavorfill",
	 "iconfavor",
	 "iconloading",
	 "iconlocationfill",
	 "iconlocation",
	 "iconphone",
	 "iconroundcheckfill",
	 "iconroundcheck",
	 "iconroundclosefill",
	 "iconroundclose",
	 "iconroundrightfill",
	 "iconroundright",
	 "iconsearch",
	 "icontaxi",
	 "icontimefill",
	 "icontime",
	 "iconunfold",
	 "iconwarnfill",
	 "iconwarn",
	 "iconcamerafill",
	 "iconcamera",
	 "iconcommentfill",
	 "iconcomment",
	 // "iconlikefill",
	 // "iconlike",
	 // "iconnotificationfill",
	 // "iconnotification",
	 // "iconorder",
	 // "iconsamefill",
	 // "iconsame",
	 // "icondeliver",
	 // "iconevaluate",
	 // "iconpay",
	 // "iconsend",
	 // "iconshop",
	 // "iconticket",
	 // "iconwang",
	 // "iconback",
	 // "iconcascades",
	 // "icondiscover",
	 // "iconlist",
	 // "iconmore",
	 // "iconscan",
	 // "iconsettings",
	 // "iconquestionfill",
	 // "iconquestion",
	 // "iconshopfill",
	 // "iconform",
	 // "iconwangfill",
	 // "iconpic",
	 // "iconfilter",
	 // "iconfootprint",
	 // "icontop",
	 // "iconpulldown",
	 // "iconpullup",
	 // "iconright",
	 // "iconrefresh",
	 // "iconmoreandroid",
	 // "icondeletefill",
	 // "iconrefund",
	 // "iconcart",
	 // "iconqrcode",
	 // "iconremind",
	 // "icondelete",
	 // "iconprofile",
	 // "iconhome",
	 // "iconcartfill",
	 // "icondiscoverfill",
	 // "iconhomefill",
	 // "iconmessage",
	 // "iconaddressbook",
	 // "iconlink",
	 // "iconlock",
	 // "iconunlock",
	 // "iconvip",
	 // "iconweibo",
	 // "iconactivity",
	 // "iconbig",
	 // "iconfriendaddfill",
	 // "iconfriendadd",
	 // "iconfriendfamous",
	 // "iconfriend",
	 // "icongoods",
	 // "iconselection",
	 // "icontmall",
	 // "iconexplore",
	 // "iconpresent",
	 // "iconsquarecheckfill",
	 // "iconsquare",
	 // "iconsquarecheck",
	 // "iconround",
	 // "iconroundaddfill",
	 // "iconroundadd",
	 // "iconadd",
	 // "iconnotificationforbidfill",
	 // "iconexplorefill",
	 // "iconfold",
	 // "icongame",
	 // "iconredpacket",
	 // "iconselectionfill",
	 // "iconsimilar",
	 // "iconappreciatefill",
	 // "iconinfofill",
	 // "iconinfo",
	 // "icontao",
	 // "iconmobiletao",
	 // "iconforwardfill",
	 // "iconforward",
	 // "iconrechargefill",
	 // "iconrecharge",
	 // "iconvipcard",
	 // "iconvoice",
	 // "iconvoicefill",
	 // "iconfriendfavor",
	 // "iconwifi",
	 // "iconshare",
	 // "iconwefill",
	 // "iconwe",
	 // "iconlightauto",
	 // "iconlightforbid",
	 // "iconlightfill",
	 // "iconcamerarotate",
	 // "iconlight",
	 // "iconbarcode",
	 // "iconflashlightclose",
	 // "iconflashlightopen",
	 // "iconsearchlist",
	 // "iconservice",
	 // "iconsort",
	 // "icon1212",
	 // "icondown",
	 // "iconmobile",
	 // "iconmobilefill",
	 // "iconcopy",
	 // "iconcountdownfill",
	 // "iconcountdown",
	 // "iconnoticefill",
	 // "iconnotice",
	 // "iconqiang",
	 // "iconupstagefill",
	 // "iconupstage",
	 // "iconbabyfill",
	 // "iconbaby",
	 // "iconbrandfill",
	 // "iconbrand",
	 // "iconchoicenessfill",
	 // "iconchoiceness",
	 // "iconclothesfill",
	 // "iconclothes",
	 // "iconcreativefill",
	 // "iconcreative",
	 // "iconfemale",
	 // "iconkeyboard",
	 // "iconmale",
	 // "iconnewfill",
	 // "iconnew",
	 // "iconpullleft",
	 // "iconpullright",
	 // "iconrankfill",
	 // "iconrank",
	 // "iconbad",
	 // "iconcameraadd",
	 // "iconfocus",
	 // "iconfriendfill",
	 // "iconcameraaddfill",
	 // "iconapps",
	 // "iconpaintfill",
	 // "iconpaint",
	 // "iconpicfill",
	 // "iconrefresharrow",
	 // "iconmarkfill",
	 // "iconmark",
	 // "iconpresentfill",
	 // "iconrepeal",
	 // "iconalbum",
	 // "iconpeoplefill",
	 // "iconpeople",
	 // "iconservicefill",
	 // "iconrepair",
	 // "iconfile",
	 // "iconrepairfill",
	 // "icontaoxiaopu",
	 // "iconattentionfill",
	 // "iconattention",
	 // "iconcommandfill",
	 // "iconcommand",
	 // "iconcommunityfill",
	 // "iconcommunity",
	 // "iconread",
	 // "iconsuan",
	 // "iconhua",
	 // "iconju",
	 // "icontian",
	 // "iconcalendar",
	 // "iconcut",
	 // "iconmagic",
	 // "iconbackwardfill",
	 // "iconplayfill",
	 // "iconstop",
	 // "icontagfill",
	 // "icontag",
	 // "icongroup",
	 // "iconall",
	 // "iconbackdelete",
	 // "iconhotfill",
	 // "iconhot",
	 // "iconpost",
	 // "iconradiobox",
	 // "iconrounddown",
	 // "iconupload",
	 // "iconwritefill",
	 // "iconwrite",
	 // "iconradioboxfill",
	 // "iconpunch",
	 // "iconshake",
	 // "iconadd1",
	 // "iconmove",
	 // "iconsafe",
	 // "iconhaodian",
	 // "iconmao",
	 // "iconqi",
	 // "iconye",
	 // "iconjuhuasuan",
	 // "icontaoqianggou",
	 // "icontianmao",
	 // "iconactivityfill",
	 // "iconcrownfill",
	 // "iconcrown",
	 // "icongoodsfill",
	 // "iconmessagefill",
	 // "iconprofilefill",
	 // "iconsound",
	 // "iconsponsorfill",
	 // "iconsponsor",
	 // "iconupblock",
	 // "iconweblock",
	 // "iconweunblock",
	 // "icon1111",
	 // "iconmy",
	 // "iconmyfill",
	 // "iconemojifill",
	 // "iconemojiflashfill",
	 // "iconflashbuyfill-copy",
	 // "icontext",
	 // "icongoodsfavor",
	 // "iconmusicfill",
	 // "iconmusicforbidfill",
	 // "iconxiamiforbid",
	 // "iconxiami",
	 // "iconroundleftfill",
	 // "icontriangledownfill",
	 // "icontriangleupfill",
	 // "iconroundleftfill-copy",
	 // "iconpulldown1",
	 // "iconemojilight",
	 // "iconkeyboardlight",
	 // "iconrecordfill",
	 // "iconrecordlight",
	 // "iconrecord",
	 // "iconroundaddlight",
	 // "iconsoundlight",
	 // "iconcardboardfill",
	 // "iconcardboard",
	 // "iconformfill",
	 // "iconcoin",
	 // "iconsortlight",
	 // "iconcardboardforbid",
	 // "iconcirclefill",
	 // "iconcircle",
	 // "iconattentionforbid",
	 // "iconattentionforbidfill",
	 // "iconattentionfavorfill",
	 // "iconattentionfavor",
	 // "iconpiclight",
	 // "iconshoplight",
	 // "iconvoicelight",
	 // "iconattentionfavorfill-copy",
	 // "iconfull",
	 // "iconmail",
	 // "iconpeoplelist",
	 // "icongoodsnewfill",
	 // "icongoodsnew",
	 // "iconmedalfill",
	 // "iconmedal",
	 // "iconnewsfill",
	 // "iconnewshotfill",
	 // "iconnewshot",
	 // "iconnews",
	 // "iconvideofill",
	 // "iconvideo",
	 // "iconaskfill",
	 // "iconask",
	 // "iconexit",
	 // "iconskinfill",
	 // "iconskin",
	 // "iconmoneybagfill",
	 // "iconusefullfill",
	 // "iconusefull",
	 // "iconmoneybag",
	 // "iconredpacket_fill",
	 // "iconsubscription",
	 // "iconhome_light",
	 // "iconmy_light",
	 // "iconcommunity_light",
	 // "iconcart_light",
	 // "iconwe_light",
	 // "iconhome_fill_light",
	 // "iconcart_fill_light",
	 // "iconcommunity_fill_light",
	 // "iconmy_fill_light",
	 // "iconwe_fill_light",
	 // "iconskin_light",
	 // "iconsearch_light",
	 // "iconscan_light",
	 // "iconpeople_list_light",
	 // "iconmessage_light",
	 // "iconclose_light",
	 // "iconadd_light",
	 // "iconprofile_light",
	 // "iconservice_light",
	 // "iconfriend_add_light",
	 // "iconedit_light",
	 // "iconcamera_light",
	 // "iconhot_light",
	 // "iconrefresh_light",
	 // "iconback_light",
	 // "iconshare_light",
	 // "iconcomment_light",
	 // "iconappreciate_light",
	 // "iconfavor_light",
	 // "iconappreciate_fill_light",
	 // "iconcomment_fill_light",
	 // "iconwang_light",
	 // "iconmore_android_light",
	 // "iconfriend_light",
	 // "iconmore_light",
	 // "icongoods_favor_light",
	 // "icongoods_new_fill_light",
	 // "icongoods_new_light",
	 // "icongoods_light",
	 // "iconmedal_fill_light",
	 // "iconmedal_light",
	 // "iconnews_fill_light",
	 // "iconnews_hot_fill_light",
	 // "iconnews_hot_light",
	 // "iconnews_light",
	 // "iconvideo_fill_light",
	 // "iconmessage_fill_light",
	 // "iconform_light",
	 // "iconvideo_light",
	 // "iconsearch_list_light",
	 // "iconform_fill_light",
	 // "iconglobal_light",
	 // "iconglobal",
	 // "iconfavor_fill_light",
	 // "icondelete_light",
	 // "iconback_android",
	 // "iconback_android_light",
	 // "icondown_light",
	 // "iconround_close_light",
	 // "iconround_close_fill_light",
	 // "iconexpressman",
	 // "iconpunch_light",
	 // "iconevaluate_fill",
	 // "iconfurniture",
	 // "icondress",
	 // "iconcoffee",
	 // "iconsports",
	 // "icongroup_light",
	 // "iconlocation_light",
	 // "iconattention_light",
	 // "icongroup_fill_light",
	 // "icongroup_fill",
	 // "iconplay_forward_fill",
	 // "iconsubscription_light",
	 // "icondeliver_fill",
	 // "iconnotice_forbid_fill",
	 // "iconqr_code_light",
	 // "iconsettings_light",
	 // "iconpick",
	 // "iconform_favor_light",
	 // "iconround_comment_light",
	 // "iconphone_light",
	 // "iconround_down_light",
	 // "iconfriend_settings_light",
	 // "iconchange",
	 // "iconround_list_light",
	 // "iconticket_fill",
	 // "iconround_friend_fill",
	 // "iconround_crown_fill",
	 // "iconround_link_fill",
	 // "iconround_light_fill",
	 // "iconround_favor_fill",
	 // "iconround_menu_fill",
	 // "iconround_location_fill",
	 // "iconround_pay_fill",
	 // "iconround_like_fill",
	 // "iconround_people_fill",
	 // "iconround_pay",
	 // "iconround_rank_fill",
	 // "iconround_redpacket_fill",
	 // "iconround_skin_fill",
	 // "iconround_record_fill",
	 // "iconround_ticket_fill",
	 // "iconround_redpacket",
	 // "iconround_text_fill",
	 // "iconround_ticket",
	 // "iconround_transfer_fill",
	 // "iconsubtitle_block_light",
	 // "iconwarn_light",
	 // "iconround_transfer",
	 // "iconvip_code_light",
	 // "iconsubtitle_unblock_light",
	 // "iconround_shop_fill",
	 // "iconoppose_fill_light",
	 // "iconoppose_light",
	 // "iconliving",
	 // "icongoods_hot_fill",
	 // "iconticket_money_fill",
	 // "iconarrow_left_fill",
	 // "iconarrow_up_fill",
	 // "iconxiaoheiqun",
	 // "iconauction",
];


export default {}




var span = document.querySelectorAll('.font-class  .code-name');
for (var i = 0, len = span.length; i < len; i++) {
	console.log('"' + (span[i].innerText).slice(1) + '",');
}