/**
 * Created by Seven on 2019/3/30.
 * project: AutumnUI
 * email: fighting20xx@126.com
 */


export const iconList = [
	"icon-accessory",
	"icon-activity",
	"icon-activity_fill",
	"icon-add",
	"icon-addition_fill",
	"icon-addition",
	"icon-addpeople_fill",
	"icon-addpeople",
	"icon-addressbook_fill",
	"icon-addressbook",
	"icon-barrage_fill",
	"icon-barrage",
	"icon-browse_fill",
	"icon-browse",
	"icon-brush",
	"icon-brush_fill",
	"icon-businesscard_fill",
	"icon-businesscard",
	"icon-camera_fill",
	"icon-camera",
	"icon-clock_fill",
	"icon-clock",
	"icon-close",
	// "icon-collection_fill",           //先暂时隐藏不显示，影响页面布局
	// "icon-collection",
	// "icon-computer_fill",
	// "icon-computer",
	// "icon-coordinates_fill",
	// "icon-coordinates",
	// "icon-coupons_fill",
	// "icon-coupons",
	// "icon-createtask_fill",
	// "icon-createtask",
	// "icon-customerservice_fill",
	// "icon-customerservice",
	// "icon-delete_fill",
	// "icon-delete",
	// "icon-document",
	// "icon-document_fill",
	// "icon-dynamic_fill",
	// "icon-dynamic",
	// "icon-editor",
	// "icon-eit",
	// "icon-emoji_fill",
	// "icon-emoji",
	// "icon-empty",
	// "icon-empty_fill",
	// "icon-enter",
	// "icon-enterinto",
	// "icon-enterinto_fill",
	// "icon-feedback_fill",
	// "icon-feedback",
	// "icon-flag_fill",
	// "icon-flag",
	// "icon-flashlight",
	// "icon-flashlight_fill",
	// "icon-flip",
	// "icon-flip_fill",
	// "icon-fullscreen",
	// "icon-group",
	// "icon-group_fill",
	// "icon-headlines_fill",
	// "icon-headlines",
	// "icon-homepage_fill",
	// "icon-homepage",
	// "icon-integral_fill",
	// "icon-integral",
	// "icon-interactive_fill",
	// "icon-interactive",
	// "icon-keyboard",
	// "icon-label",
	// "icon-label_fill",
	// "icon-like_fill",
	// "icon-like",
	// "icon-live_fill",
	// "icon-live",
	// "icon-lock_fill",
	// "icon-lock",
	// "icon-mail",
	// "icon-mail_fill",
	// "icon-manage_fill",
	// "icon-manage",
	// "icon-message",
	// "icon-message_fill",
	// "icon-mine",
	// "icon-mine_fill",
	// "icon-mobilephone_fill",
	// "icon-mobilephone",
	// "icon-more",
	// "icon-narrow",
	// "icon-offline_fill",
	// "icon-offline",
	// "icon-order_fill",
	// "icon-order",
	// "icon-other",
	// "icon-people_fill",
	// "icon-people",
	// "icon-picture_fill",
	// "icon-picture",
	// "icon-play",
	// "icon-play_fill",
	// "icon-playon_fill",
	// "icon-playon",
	// "icon-praise_fill",
	// "icon-praise",
	// "icon-prompt_fill",
	// "icon-prompt",
	// "icon-qrcode_fill",
	// "icon-qrcode",
	// "icon-redpacket_fill",
	// "icon-redpacket",
	// "icon-refresh",
	// "icon-remind_fill",
	// "icon-remind",
	// "icon-return",
	// "icon-right",
	// "icon-scan",
	// "icon-select_fill",
	// "icon-select",
	// "icon-send",
	// "icon-service_fill",
	// "icon-service",
	// "icon-setup_fill",
	// "icon-setup",
	// "icon-share_fill",
	// "icon-share",
	// "icon-shielding_fill",
	// "icon-shielding",
	// "icon-smallscreen_fill",
	// "icon-smallscreen",
	// "icon-stealth_fill",
	// "icon-stealth",
	// "icon-success_fill",
	// "icon-success",
	// "icon-suspend",
	// "icon-switch",
	// "icon-systemprompt_fill",
	// "icon-systemprompt",
	// "icon-tailor",
	// "icon-task",
	// "icon-task_fill",
	// "icon-tasklist_fill",
	// "icon-tasklist",
	// "icon-text",
	// "icon-time_fill",
	// "icon-time",
	// "icon-translation_fill",
	// "icon-translation",
	// "icon-trash",
	// "icon-trash_fill",
	// "icon-undo",
	// "icon-unlock_fill",
	// "icon-unlock",
	// "icon-video",
	// "icon-video_fill",
	// "icon-warning_fill",
	// "icon-warning",
	// "icon-workbench_fill",
	// "icon-workbench",
	// "icon-search",
	// "icon-searchfill",
	// "icon-qianniu",
	// "icon-publishgoods_fill",
	// "icon-shop_fill",
	// "icon-transaction_fill",
	// "icon-packup",
	// "icon-unfold",
	// "icon-wangwang",
	// "icon-financial_fill",
	// "icon-marketing_fill",
	// "icon-shake",
	// "icon-decoration_fill",
	// "icon-budaidise",
	// "icon-qianniudaidise",
	// "icon-questions",
	// "icon-supply",
	// "icon-tools",
	// "icon-int",
	// "icon-commodity",
	// "icon-zhtn",
];


export default {}




// var span = document.querySelectorAll('.font-class  .code-name');
// for (var i = 0, len = span.length; i < len; i++) {
// 	console.log('"' + (span[i].innerText).slice(1) + '",');
// }